- name: xqueue | restart xqueue
  supervisorctl: >
    name={{ item }}
    supervisorctl_path={{ supervisor_ctl }}
    config={{ supervisor_cfg }}
    state=restarted
  with_items:
  - xqueue
  - xqueue_consumer
  tags: deploy
