---
- hosts: first_in_tag_role_mongo
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - role: 'mongo'
      mongo_create_users: yes
#- hosts: tag_role_mongo:!first_in_tag_role_mongo
#  sudo: True
#  vars_files:
#    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
#    - "{{ secure_dir }}/vars/common/common.yml"
#  roles:
#    - common
#    - gh_users
#    - mongo
- hosts: first_in_tag_role_edxapp
  sudo: True
  serial: 1
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - datadog
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
    - role: 'edxapp'
      edxapp_lms_env: 'lms.envs.load_test'
      migrate_db: 'yes'
      openid_workaround: 'yes'
    - splunkforwarder
- hosts: tag_role_edxapp:!first_in_tag_role_edxapp
  sudo: True
  serial: 1
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - datadog
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
    - role: 'edxapp'
      edxapp_lms_env: 'lms.envs.load_test'
    - splunkforwarder
- hosts: tag_role_worker
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - datadog
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
    - role: 'edxapp'
      edxapp_lms_env: 'lms.envs.load_test'
      celery_worker: True
    - splunkforwarder
- hosts: tag_role_xserver
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - supervisor
    - role: nginx
      nginx_sites:
      - xserver
    - xserver
    - splunkforwarder
- hosts: tag_role_rabbitmq
  serial: 1
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - supervisor
    - rabbitmq
    - splunkforwarder
- hosts: first_in_tag_role_xqueue
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - supervisor
    - role: nginx
      nginx_sites:
      - xqueue
    - role: xqueue
      migrate_db: 'yes'
    - splunkforwarder
- hosts: tag_role_xqueue:!first_in_tag_role_xqueue
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - supervisor
    - role: nginx
      nginx_sites:
      - xqueue
    - xqueue
    - splunkforwarder
- hosts: tag_role_forum
  sudo: True
  vars_files:
    - "{{ secure_dir }}/vars/{{ENVIRONMENT}}/{{CLOUDFORMATION_STACK_NAME}}.yml"
    - "{{ secure_dir }}/vars/common/common.yml"
  roles:
    - common
    - gh_users
    - supervisor
    - oraclejdk
    - elasticsearch
    - forum
