---

# This playbook is to configuration
# the official edX sandbox instance
# sandbox.edx.org

- name: Configure instance(s)
  hosts: tag_Name_edx-sandbox
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    mysql5_workaround: True
  roles:
    - common
    - supervisor
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
    - edxlocal
    - mongo
    - edxapp
    - rabbitmq
    - oraclejdk
    - elasticsearch
    - { role: 'edxapp', celery_worker: True }
    - role: rbenv
      rbenv_user: "{{ forum_user }}"
      rbenv_dir: "{{ forum_home }}"
      rbenv_ruby_version: "{{ forum_ruby_version }}"
    - forum
