---

- name: notifier | restart notifier-scheduler
  supervisorctl: >
    name=notifier-scheduler
    state=restarted
    config={{ supervisor_cfg }}
    supervisorctl_path={{ supervisor_ctl }}
  tags: deploy

- name: notifier | restart notifier-celery-workers
  supervisorctl: >
    name=notifier-celery-workers
    state=restarted
    config={{ supervisor_cfg }}
    supervisorctl_path={{ supervisor_ctl }}
  tags: deploy
