- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_commit: 'master'
  vars_files:
    - "group_vars/all"
  roles:
    - gh_users
    - common
    - role: nginx
      nginx_sites:
      - cms
      - lms
      - ora
      - xqueue
    - edxlocal
    - supervisor
    - mongo
    - edxapp
    - demo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - { role: 'edxapp', celery_worker: True }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: "xqueue", update_users: True }
    - ora
    - discern
