- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
  vars_files:
    - "group_vars/all"
  roles:
    - common
    - role: nginx
      nginx_sites:
      - lms
      - cms
      - lms-preview
    - edxlocal
    - supervisor
    - mongo
    - edxapp
    - oraclejdk
    - elasticsearch
    - { role: 'edxapp', celery_worker: True }
    - forum
