- name: Configure instance(s)
  hosts: vagrant
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    devstack: True
    edx_platform_commit: 'master'
    mongo_enable_journal: False
  vars_files:
    - "group_vars/all"
  roles:
    - common
    - edxlocal
    - mongo
    - edxapp
    - oraclejdk
    - elasticsearch
    - forum
    - browsers
    - local_dev
